### ISSUE TITLE
One-class classification

### ISSUE THREAD

**Issue by henrique** [xlvector/hector#26]
Hi Xiang Liang,

First thanks for sharing your code here.
Have you tried to use any of your algorithms for one-class classification problems?

Basically what I have is something like:
1   1:0.7 3:0.1 9:0.4
1   2:0.3 4:0.9 7:0.5
1   2:0.7 5:0.3
1 ...

I've tried most of the methods available but they always return AUC: 0.5
Thanks already for any tips.

Cheers,
Henrique

**Comment by xlvector** [comment]
Sorry for later reply. Hector does not support one-class classification now.
